"""message

Revision ID: 307d2d5c2a1e
Revises: 6f1fb132ba7a
Create Date: 2023-07-17 11:25:12.516181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307d2d5c2a1e'
down_revision = '6f1fb132ba7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_cards', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
