"""message

Revision ID: 6f1fb132ba7a
Revises: 0186ad7172cf
Create Date: 2023-07-17 11:12:44.224205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1fb132ba7a'
down_revision = '0186ad7172cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_cards', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('card_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_cards', schema=None) as batch_op:
        batch_op.alter_column('card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
